FROM ubuntu:18.04
RUN apt-get update -y
RUN apt-get install -y python python-pip 
RUN apt-get install -y net-tools vim
RUN apt-get install -y libc++-dev
RUN pip install mcstatus ec2-metadata boto3

CMD ["bash"]
